### ISSUE TITLE
Assimp model loader

### ISSUE THREAD

**Issue by istepka** [rswc/tower_defense#2]
Research 
- How to create animations?
- Implementation

**Comment by istepka** [comment]
Wygląda na to, że jest problem z wczytywaniem tekstur na model. Odczyt z plików .png i .obj/.fbx/etc.. jest raczej poprawny. Tekstury są załadowane. Model jest poprawnie załadowany i wyświetlony. Shader teoretycznie obsługuje tekstury. Jednak w efekcie na ekranie pojawia się szary model bez tekstury.

Testowałem na innych modelach i czasami tekstura się wczytuje, ale wygląda wtedy jakby była źle zmapowana. To znaczy, że pojawiają się kolory na modelu, ale są niepoprawne.  

@rswc możesz rzucić okiem na shader / jednostkę teksturującą / wczytywanie do shadera w `assimpobject.cpp`?

**Comment by rswc** [comment]
Mówisz o wersji na master teraz? Widzę że sampler w shaderze się nazywa "tex", a assimpobject ustawia uniform "textureMap0".

Jak to nie to, to podrzuć model jakiś na którym widać że nie działa.

**Comment by istepka** [comment]
Rzeczywiście, to był błąd + literówka w texCoord(s). Już jest okej.
