### ISSUE TITLE
Rotation-independent camera movement

### ISSUE THREAD

**Issue by rswc** [rswc/tower_defense#7]
Since, in the current version, camera height capping is done _after_ adding the front vector to position, movement speed along that axis is dependent on rotation. Try moving forward while looking down for an example.

We should consider instead explicitly casting the forward vector to the XZ-plane and normalizing _before_ adding to position, whenever height cap is enabled (or any other solution which does not needlessly constrain movement speed).

**Comment by istepka** [comment]
Dodałem casting na XZ przed wyliczeniem CameraPos. Height capping może zostać później. Powinno działać poprawnie z najnowszym commitem.
```
cameraFront.y = 0;    
cameraFront = glm::normalize(cameraFront);
```

**Comment by rswc** [comment]
Tylko teraz limitu wysokości nie da się wyłączyć...
Poza tym ustawianie Y na wartość stałej co klatkę jest raczej zbędne jak mamy spłaszczony wektor w przód.

**Comment by istepka** [comment]
Przeniosłem ustawianie Y na toggle height capa. 
Limit wysokości usunąłem z free flight.
